---
title: "MUKUNDANANDA YOGA FEST"
date: 2022-06-07
--
title: INSPIRON
theme: minima
author: GitHub User
email: yoyo@inpiron.com
description: > # this means to ignore newlines until "baseurl:"
 The term front matter refers to YAML metadata that prepends the 
 content of a file. For Jekyll, this includes generator instructions 
 to indicate the layout style of a Markdown page (post, page, and so on). 
 It may also include page metadata, such as the document title, or page content
 variables, such as a blog post's author

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
